version: 0.0
os: linux

files:
  - source: index.html
    destination: /home/ec2-user/
  - source: requirements.txt
    destination: /home/ec2-user/
  - source: backend.py
    destination: /home/ec2-user/

permissions:
  - object: /home/ec2-user/
    pattern: "**/*"
    owner: ec2-user
    group: ec2-user
    mode: 755

phases:
  deploy_frontend:
    commands:
      - echo "Deploy frontend service..."
      - aws s3 cp /home/ec2-user/index.html s3://onion.halykmart.live/index.html

  deploy_backend:
    commands:
      - pip3 install -r /home/ec2-user/requirements.txt
      - echo "Starting the backend service..."
      - python /home/ec2-user/backend.py
