version: 0.0
os: linux

phases:
  pre-deploy:
    commands:
      - cd /home/ssm-user/just

  deploy_frontend:
    commands:
      - echo "Deploy frontend service..."
      - aws s3 sync . s3://onion.halykmart.live/* \
        --exclude ".git*" --exclude "README.md" --exclude "*.py" --exclude "*.yml" --exclude "*.txt"
        
  deploy_backend:
    commands:
      - pip install -r requirements.txt
      - echo "Starting the backend service..."
      - python backend.py
