version: 0.2

phases:
  deploy_frontend:
    commands:
      - aws s3 sync . s3://onion.halykmart.live/ \
        --exclude ".git*" --exclude "README.md" --exclude "*.py" --exclude "*.yml" --exclude "*.txt"
 
  deploy_backend:
    commands:
      - python /project/backend.py
