version: 0.0
os: linux

files:
  - source: scripts/after_install.sh
    destination: /opt/codedeploy-agent/deployment-root/47315dd5-d2f1-4eae-a0a4-3db8436ebab2/d-EG1L9LST1/deployment-archive/home/ec2-user/
  - source: index.html
    destination: /home/ec2-user/
  - source: requirements.txt
    destination: /home/ec2-user/
  - source: backend.py
    destination: /home/ec2-user/

hooks:
  AfterInstall:
    - location: /opt/codedeploy-agent/deployment-root/47315dd5-d2f1-4eae-a0a4-3db8436ebab2/d-EG1L9LST1/deployment-archive/home/ec2-user/after_install.sh
      timeout: 300
      runas: root

phases:    
  deploy_frontend:
    commands:
      - echo "Deploy frontend service..."
      - aws s3 cp /home/ec2-user/index.html s3://onion.halykmart.live/index.html
      
  deploy_backend:
    commands:
      - pip3 install -r /home/ec2-user/requirements.txt
      - echo "Starting the backend service..."
      - python /home/ec2-user/backend.py
