version: 0.2

phases:
  deploy_frontend:
    commands:
      - echo "Deploy frontend service..."
      - aws s3 sync . s3://onion.halykmart.live/ \
        --exclude ".git*" --exclude "README.md" --exclude "*.py" --exclude "*.yml" --exclude "*.txt"
      - echo "Finish!"
 
  deploy_backend:
    commands:
      - echo "Starting the backend service..."
      - python backend.py
      - echo "Finish!"
