name: Auto-deploy index.html to Onion Domains

on:
  push:
    branches:
      - develop
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Domain
        id: set_domain
        run: |
          if [[ $GITHUB_REF == "refs/heads/develop" ]]; then
            DEPLOY_DOMAIN="dev-onion.halykmart.live"
          elif [[ $GITHUB_REF == "refs/tags/"* ]]; then
            DEPLOY_DOMAIN="onion.halykmart.live"
          else
            echo "Invalid branch/tag for deployment"
            exit 1
          fi
          echo "DEPLOY_DOMAIN=$DEPLOY_DOMAIN" >> $GITHUB_ENV

      - name: Deploy index.html
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp index.html s3://${{ env.DEPLOY_DOMAIN }}/index.html
