name: Deploy to Onion Domains

on:
  push:
    branches:
      - develop
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Domain
        id: set_domain
        run: |
          if [[ $GITHUB_REF == "refs/heads/develop" ]]; then
            echo "DEPLOY_DOMAIN=dev-onion.halykmart.live" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == "refs/tags/"* ]]; then
            echo "DEPLOY_DOMAIN=onion.halykmart.live" >> $GITHUB_ENV
          else
            echo "Invalid branch/tag for deployment"
            exit 1
          fi

      - name: Deploy to Domain
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./ s3://${{ env.DEPLOY_DOMAIN }}/ --delete
