name: S3 Deployment

on:
  push:
    branches:
      - develop
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to S3
        run: |
          if [ -n "$GITHUB_REF_NAME" ]; then
            if [ "$GITHUB_REF_NAME" == "refs/heads/develop" ]; then
              aws s3 sync index.html s3://dev-onion.halykmart.live
            elif [ "$GITHUB_REF_NAME" == "refs/tags/${{ github.event.release.tag_name }}" ]; then
              aws s3 sync index.html s3://onion.halykmart.live
            fi
          fi
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
