name: Auto-deploy repo to S3 bucket

on:
  push:
    branches:
        - static

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Domain
        id: set_domain
        run: |
          if [[ $GITHUB_REF == "refs/heads/static" ]]; then
            DEPLOY_DOMAIN="onion.halykmart.live"
          else
            echo "Invalid branch for deployment"
            exit 1
          fi
          echo "DEPLOY_DOMAIN=$DEPLOY_DOMAIN" >> $GITHUB_ENV

      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync . s3://${{ env.DEPLOY_DOMAIN }} \
            --exclude "README.md" --exclude ".git*"          
